---
name: POE-Component-SimpleDBI
version: 1.25
author:
  - 'Apocalypse <APOCAL@cpan.org>'
abstract: Asynchronous non-blocking DBI calls in POE made simple
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.30
  Error: 0.15
  POE: 0
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Session: 0
  POE::Wheel::Run: 0
  Test::More: 0.86
dynamic_config: 0
provides:
  POE::Component::SimpleDBI:
    file: lib/POE/Component/SimpleDBI.pm
    version: 1.25
  POE::Component::SimpleDBI::SubProcess:
    file: lib/POE/Component/SimpleDBI/SubProcess.pm
    version: 13
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
