---
abstract: 'Asynchronous non-blocking DBI calls in POE made simple'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SimpleDBI
provides:
  POE::Component::SimpleDBI:
    file: lib/POE/Component/SimpleDBI.pm
    version: 1.28
  POE::Component::SimpleDBI::SubProcess:
    file: lib/POE/Component/SimpleDBI/SubProcess.pm
    version: 1.28
requires:
  DBI: 1.30
  Error: 0.15
  POE: 0
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Session: 0
  POE::Wheel::Run: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.28
